name: Build and Deploy Web Application

on:
  push:
    branches:
      - main  # Trigger on push to main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_TOKEN }}

    - name: Build and push Docker image
      run: |
        # Build the Docker image and push it to Docker Hub
        docker build -t ${{ secrets.DOCKER_USERNAME }}/app:my-web-app .
        docker push ${{ secrets.DOCKER_USERNAME }}/app:my-web-app

  deploy:
    runs-on: ubuntu-latest
    needs: build 

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up SSH connection and deploy to EC2
      run: |
        # Save the private key and set proper permissions
        echo "${{ secrets.EC2_PRIVATE_KEY }}" > key.pem
        chmod 600 key.pem

        # SSH into the EC2 instance and deploy the Docker container
        ssh -i key.pem -o StrictHostKeyChecking=no ${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_HOST }} << 'EOF'
          # Stop and remove any existing container
          docker stop my-running-web-app || true
          docker rm my-running-web-app || true

          # Pull the new Docker image from Docker Hub and run it
          docker pull ${{ secrets.DOCKER_USERNAME }}/app:my-web-app
          docker run -d -p 80:80 --name my-running-web-app ${{ secrets.DOCKER_USERNAME }}/app:my-web-app
        EOF
